---
abstract: 'Value class for URIs'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Value-URI
provides:
  Class::Value::URI:
    file: lib/Class/Value/URI.pm
    version: 1.100840
  Class::Value::URI::fax:
    file: lib/Class/Value/URI/fax.pm
    version: 1.100840
  Class::Value::URI::fax_TEST:
    file: lib/Class/Value/URI/fax_TEST.pm
    version: 1.100840
  Class::Value::URI::file:
    file: lib/Class/Value/URI/file.pm
    version: 1.100840
  Class::Value::URI::file_TEST:
    file: lib/Class/Value/URI/file_TEST.pm
    version: 1.100840
  Class::Value::URI::ftp:
    file: lib/Class/Value/URI/ftp.pm
    version: 1.100840
  Class::Value::URI::ftp_TEST:
    file: lib/Class/Value/URI/ftp_TEST.pm
    version: 1.100840
  Class::Value::URI::http:
    file: lib/Class/Value/URI/http.pm
    version: 1.100840
  Class::Value::URI::http_TEST:
    file: lib/Class/Value/URI/http_TEST.pm
    version: 1.100840
requires:
  Carp: 0
  Class::Accessor::Complex: 0
  Class::Value::SemanticAdapter: 0
  Class::Value::Test: 0
  Data::Semantic::URI::TestData::fax: 0
  Data::Semantic::URI::TestData::file: 0
  Data::Semantic::URI::TestData::ftp: 0
  Data::Semantic::URI::TestData::http: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::CompanionClasses: 0
  Test::More: 0.88
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Class-Value-URI
  homepage: http://search.cpan.org/dist/Class-Value-URI/
  repository: http://github.com/hanekomu/Class-Value-URI
version: 1.100840
