--- 
abstract: ~
author: 
  - "{% ELSE %}"
build_requires: 
  Test::CompanionClasses: 0.03
  Test::Compile: 0
  Test::More: 0
  UNIVERSAL::require: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Class-Value-URI
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Complex: 0
  Class::Value::SemanticAdapter: 0
  Data::Semantic::URI: 0
  perl: 5.6.0
version: 0.02
